/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElTag: typeof import('element-plus/es')['ElTag']
    Footer: typeof import('./src/components/footer/src/footer.vue')['default']
    Navbar: typeof import('./src/components/navbar/src/navbar.vue')['default']
    NavScreen: typeof import('./src/components/navbar/src/nav-screen.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toc: typeof import('./src/components/toc/src/toc.vue')['default']
    TocContent: typeof import('./src/components/toc/src/toc-content.vue')['default']
    TocItem: typeof import('./src/components/toc/src/toc-item.vue')['default']
    TocItemWrap: typeof import('./src/components/toc/src/toc-item-wrap.vue')['default']
  }
}
