/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Comment: typeof import('./src/components/comment/src/comment.vue')['default']
    Dosearch: typeof import('./src/components/dosearch/src/dosearch.vue')['default']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Footer: typeof import('./src/components/footer/src/footer.vue')['default']
    GlobalSetting: typeof import('./src/components/global-setting/src/global-setting.vue')['default']
    JcDialog: typeof import('./src/components/jc-dialog/src/jc-dialog.vue')['default']
    JcDrawer: typeof import('./src/components/jc-drawer/src/jc-drawer.vue')['default']
    JcLogo: typeof import('./src/components/jc-logo/src/jc-logo.vue')['default']
    LayoutBox: typeof import('./src/components/global-setting/src/layout-box.vue')['default']
    Navbar: typeof import('./src/components/navbar/src/navbar.vue')['default']
    NavbarActions: typeof import('./src/components/navbar/src/navbar-actions.vue')['default']
    NavScreen: typeof import('./src/components/navbar/src/nav-screen.vue')['default']
    OtherConfigBox: typeof import('./src/components/global-setting/src/other-config-box.vue')['default']
    PrimaryBox: typeof import('./src/components/global-setting/src/primary-box.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextErasure: typeof import('./src/components/text-erasure/src/text-erasure.vue')['default']
    Toc: typeof import('./src/components/toc/src/toc.vue')['default']
    TocContent: typeof import('./src/components/toc/src/toc-content.vue')['default']
    TocItem: typeof import('./src/components/toc/src/toc-item.vue')['default']
    TocItemWrap: typeof import('./src/components/toc/src/toc-item-wrap.vue')['default']
  }
}
