/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Comment: typeof import('./src/components/comment/src/comment.vue')['default']
    Dosearch: typeof import('./src/components/dosearch/src/dosearch.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Footer: typeof import('./src/components/footer/src/footer.vue')['default']
    JcForm: typeof import('./src/components/jc-form/src/jc-form.vue')['default']
    JcMenu: typeof import('./src/components/jc-menu/src/jc-menu.vue')['default']
    JcMenuItem: typeof import('./src/components/jc-menu/src/jc-menu-item.vue')['default']
    JcPaginator: typeof import('./src/components/jc-paginator/src/jc-paginator.vue')['default']
    JcTable: typeof import('./src/components/jc-table/src/jc-table.vue')['default']
    Navbar: typeof import('./src/components/navbar/src/navbar.vue')['default']
    NavbarActions: typeof import('./src/components/navbar/src/navbar-actions.vue')['default']
    NavScreen: typeof import('./src/components/navbar/src/nav-screen.vue')['default']
    PageContent: typeof import('./src/components/page-content/src/page-content.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextErasure: typeof import('./src/components/text-erasure/src/text-erasure.vue')['default']
    Toc: typeof import('./src/components/toc/src/toc.vue')['default']
    TocContent: typeof import('./src/components/toc/src/toc-content.vue')['default']
    TocItem: typeof import('./src/components/toc/src/toc-item.vue')['default']
    TocItemWrap: typeof import('./src/components/toc/src/toc-item-wrap.vue')['default']
  }
}
